"""
This module contains the main schemas for
the Mwalika Corpus. These schemas define the
structure of the data used in Qdrant.
"""

from pydantic import BaseModel, Field, ConfigDict
from enum import Enum

class CorpusItemType(str, Enum):
    """
    Enumeration of possible corpus item types.
    """

    MINISTRY = 'ministry'
    DEPARTMENT = 'department'
    AGENCY = 'agency'
    SERVICE = 'service'

class CorpusPayload(BaseModel):
    """
    Base schema for the payload of corpus items.
    This can be extended with additional fields
    specific to each item type.
    """

    model_config = ConfigDict(
        extra='forbid',
        str_strip_whitespace=True,
    )
    type: CorpusItemType = Field(
        ...,
        description=(
            'Type of the corpus item, e.g., '
            'ministry, department.'
        ),
    )
    schema_version: str = Field(
        ...,
        description=(
            'Version of the schema used for '
            'this corpus item, e.g., "1.0".'
        ),
    )
    entity_id: str = Field(
        ...,
        description=(
            'Unique identifier for the entity represented '
            'by this corpus item, such as `ministry_id` '
            'or `department_id`.'
        ),
    )

class CorpusItem(BaseModel):
    """
    Base schema for items in the Mwalika Corpus.
    """

    model_config = ConfigDict(
        extra='forbid',
    )

    id: str = Field(
        ...,
        description=(
            'Unique identifier for the corpus item, '
            'such as `ministry_id` or `department_id`.'
        ),
    )
    vector: list[float] = Field(
        ...,
        description=(
            'Embedding vector representing the corpus '
            'item, typically generated by the OpenAI API.'
        ),
    )
    payload: CorpusPayload = Field(
        ...,
        description=(
            'Structured metadata about the corpus item, '
            'including its type, schema version, and '
            'entity identifier.'
        ),
    )

class CorpusSearchResult(BaseModel):
    """
    Schema for search results returned from Qdrant.
    """

    model_config = ConfigDict(
        extra='forbid',
    )

    id: str = Field(
        ...,
        description=(
            'Unique identifier of the corpus item that '
            'matched the search query.'
        ),
    )
    score: float = Field(
        ...,
        description=(
            'Relevance score of the search result, as '
            'determined by Qdrant\'s scoring mechanism.'
        ),
    )
    payload: CorpusPayload = Field(
        ...,
        description=(
            'Structured metadata about the search result, '
            'including its type, schema version, and '
            'entity identifier.'
        ),
    )